steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'eu.gcr.io/$PROJECT_ID/platform/ci-demo:$SHORT_SHA', '.' ]
logsBucket: 'gs://ricardo-dev-ch_cloudbuild'
images:
- 'eu.gcr.io/$PROJECT_ID/platform/ci-demo:$SHORT_SHA'
