version: 2
jobs:
  deploy:
    docker:
      - image: eu.gcr.io/ricardo-dev-ch/platform/isopod:v6
        auth:
          username: _json_key
          password: $GCLOUD_SERVICE_KEY
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /root/.config/gcloud/legacy_credentials/isopod-builder@ricardo-dev-ch.iam.gserviceaccount.com/adc.json
    steps:
      - add_ssh_keys:
          fingerprints:
            - "db:02:b9:24:9d:da:2d:10:d1:f4:25:33:28:de:f2:60"
      - checkout
      - run: gcloud-auth
      - run: isopod update
      - run: isopod info
      - run: isopod build
      - run: kubeconfig
      - run: kubectl config view
      - run: kubectl get nodes
      - run: cat skaffold.yaml
      - run: isopod deploy

      # Manuak image build
      # - run: gcloud builds submit --substitutions=SHORT_SHA="${CIRCLE_SHA1::7}" .

  # job-two:
  #   docker:
  #     # - image: circleci/ruby:2.4.1
  #     - image: ruby:2.6.3
  #   steps:
  #     - checkout
  #     - run: echo "A more familiar hi"
  #     - run: ls -la
  #     - run: pwd
  #     - run: ls -l ~/
  #     - run: ls -l ~/.ssh

workflows:
  version: 2
  one_and_two:
    jobs:
      - deploy:
          context: dev-cookie
      # - job-two:
      #     requires:
      #       - job-one
