version: 2
jobs:
  deploy:
    docker:
      - image: eu.gcr.io/ricardo-dev-ch/platform/isopod:v8
        auth:
          username: _json_key
          password: $GCLOUD_SERVICE_KEY
    steps:
      - add_ssh_keys:
          fingerprints:
            - "db:02:b9:24:9d:da:2d:10:d1:f4:25:33:28:de:f2:60"
      - checkout
      - run: isopod setup
      - run: isopod ci-setup-access
      - run: isopod build
      - run: isopod deploy
      # Debug commands
      # - run: isopod info
      # - run: kubectl config view
      # - run: kubectl get nodes
      # - run: cat skaffold.yaml
      # Manual image build
      # - run: gcloud builds submit --substitutions=SHORT_SHA="${CIRCLE_SHA1::7}" .

  integration-test:
    docker:
      - image: eu.gcr.io/ricardo-dev-ch/platform/isopod:v8
        auth:
          username: _json_key
          password: $GCLOUD_SERVICE_KEY
    steps:
      - add_ssh_keys:
          fingerprints:
            - "db:02:b9:24:9d:da:2d:10:d1:f4:25:33:28:de:f2:60"
      - checkout
      - run: isopod setup
      - run: isopod ci-setup-access
      - run:
          command: isopod forward
          background: true
      - run: sleep 10
      - run: ps auxf
      - run: curl http://ci-demo-svc:8080/


workflows:
  version: 2
  one_and_two:
    jobs:
      - integration-test:
          context: dev-cookie
      # - deploy:
      #     context: dev-cookie
      # - integration-test:
      #     context: dev-cookie
      #     requires:
      #       - deploy
