version: 2
jobs:
  job-one:
    docker:
      # - image: circleci/ruby:2.4.1
      - image:  eu.gcr.io/ricardo-dev-ch/platform/isopod
        auth:
          username: _json_key
          password: $GCLOUD_SERVICE_KEY
    steps:
      - add_ssh_keys:
          fingerprints:
            - "db:02:b9:24:9d:da:2d:10:d1:f4:25:33:28:de:f2:60"
      - checkout
      - run: mkdir -p ~/.ricardo/
      - run: git clone --depth 1 git@github.com:ricardo-ch/delivery-demo.git ~/.ricardo/delivery
      - run: ls -la ~/.ricardo/delivery
  # job-two:
  #   docker:
  #     # - image: circleci/ruby:2.4.1
  #     - image: ruby:2.6.3
  #   steps:
  #     - checkout
  #     - run: echo "A more familiar hi"
  #     - run: ls -la
  #     - run: pwd
  #     - run: ls -l ~/
  #     - run: ls -l ~/.ssh

workflows:
  version: 2
  one_and_two:
    jobs:
      - job-one
      # - job-two:
      #     requires:
      #       - job-one
